variable "rgs" {}
variable "vnets" {}
variable "pips" {}
variable "subnets" {}
variable "nsgs" {}
variable "bastion" {}
variable "nics" {}
variable "nsgass" {}
variable "vms" {}
variable "keyvault" {}
variable "vaultsecrets" {}
